service: test

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    host: 0.0.0.0
  dotenv:
    path: .env.${env:NODE_ENV}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  timeout: 300

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
